const SPLASH_CONSTANT = 'Splash'
const NO_BACKGROUND_CONSTANT = 'No_Background'

const IMAGE_TYPES = [SPLASH_CONSTANT, NO_BACKGROUND_CONSTANT]

module.exports = {
  IMAGE_TYPES,
  SPLASH_CONSTANT,
  NO_BACKGROUND_CONSTANT
}

